services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    depends_on:
      - db
      - jaeger
      - redis
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=EventStafDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - ConnectionStrings__DevelopmentConnection=Server=db;Database=EventStafDb;User=sa;Password=YourStrong!Passw0rd;Encrypt=False;
      - ConnectionStrings__RedisHttp=http://redis:6379
      - ConnectionStrings__RedisGrpc=http://redis:6379
      - ConnectionStrings__Redis=redis:6379
      - MassTransit__Host=rabbitmq
      - MassTransit__Port=5672
      - MassTransit__Username=guest
      - MassTransit__Password=guest
      - MassTransit__ExpireInMinues= 30
    networks:
      - eventstaff-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - db
      - jaeger
      - redis
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=EventStafDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - ConnectionStrings__DevelopmentConnection=Server=db;Database=EventStafDb;User=sa;Password=YourStrong!Passw0rd;Encrypt=False;
      - ConnectionStrings__RedisHttp=http://redis:6379
      - ConnectionStrings__RedisGrpc=http://redis:6379
      - ConnectionStrings__Redis=http://redis:6379
      - MassTransit__Host=rabbitmq
      - MassTransit__Port=5672
      - MassTransit__Username=guest
      - MassTransit__Password=guest
      - MassTransit__ExpireInMinues= 30
    networks:
      - eventstaff-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - eventstaff-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S db -U sa -P YourStrong!Passw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 15s

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - eventstaff-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - eventstaff-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://jaeger:16686"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - eventstaff-network
    healthcheck:
      test:  rabbitmq-diagnostics -q ping 
      interval: 30s
      timeout: 30s
      retries: 3

networks:
  eventstaff-network:
    driver: bridge

volumes:
  sqldata:
    driver: local